name: VoxelSMP
version: '${version}'
main: me.creonc.voxelsmp.VoxelSMP
api-version: '1.20'
load: STARTUP
author: CreonC
description: VoxelSMP's core plugin

commands:
  settings:
    description: Opens the settings menu
    usage: /settings
