name: VoxelSMP
version: '${version}'
main: me.creonc.voxelsmp.VoxelSMP
api-version: '1.21'
load: STARTUP
author: CreonC
description: VoxelSMP's core plugin

permissions:
  voxelsmp.admin:
    description: Allows the player to use all admin commands
    default: op

commands:
  settings:
    description: Opens the settings menu
    usage: /settings
  graceperiod:
    description: Sets the grace period
    usage: /graceperiod
    aliases: gp
    permission: voxelsmp.admin
    permission-message: "You do not have permission to use this command"
  autorestart:
    description: Sets the autorestart time
    usage: /autorestart
    permission: voxelsmp.admin
    permission-message: "You do not have permission to use this command"
  deferrestart:
    description: Defers the restart
    usage: /deferrestart
    permission: voxelsmp.admin
    permission-message: "You do not have permission to use this command"
  worldcontrol:
    description: toggles nether and end portal
    usage: /worldcontrol
    permission: voxelsmp.admin
    permission-message: "You do not have permission to use this command"
  doublexp:
    description: doublexp toggler
    usage: /doublexp
    permission: voxelsmp.admin
    permission-message: "You do not have permission to use this command"

